### ISSUE TITLE
Testing multiple query parameters with the same key

### ISSUE THREAD

**Issue by Tunous** [JorgeCastilloPrz/hiroaki#50]
Let's assume that I make the following request `https://example.com/add?i=1&i=2&i=3`. Is it possible to test that the response contains all of these parameters?

I've to tried to make a test like this: `server.verify("add").called(queryParams = params("i" to "1", "i" to "2", "i" to "3")))`, but that fails because each parameter overrides previous.

I think something like this would be nice to have:
```kt
server.verify("add").called(queryParams = params("i" to listOf("1", "2", "3")))
```

**Comment by JorgeCastilloPrz** [comment]
How much sense does it have to ask for the same query parameter key but with different values on the same request? Is that something allowed in libraries like Retrofit?

I'd love to get more details on a real world usecase example since I've never needed anything similar.

Couldn't that just be a bad API design? Just asking.

**Comment by Tunous** [comment]
My issue is based on the API that I'm using and I can't change it. They use the same parameter specified few times as a way to affect multiple items from one request. You can see [an example here](http://www.inoreader.com/developers/edit-tag) under the "Examples" section:

```
https://www.inoreader.com/reader/api/0/edit-tag?a=user/-/state/com.google/read&i=12345678&i=12345679
```

I am using Retrofit in my project and this request does work when implemented like this:

```kt
@POST("edit-tag")
fun addTags(
    @Query("i") ids: List<String>,
    @Query("a") tagIds: List<String>
): Call<Void>
```

**Comment by JorgeCastilloPrz** [comment]
@Tunous, this problem has been fixed and you'll be able to assert like this when it gets released (in the following days, I wanna fix the other thing you reported before as well). Thanks for your feedback.

````kotlin
@Test(expected = AssertionError::class)
fun failsQueryParamListWithWrongValue() {
        server.whenever(Method.POST, "my-fake-service/edit-tag")
                .thenRespond(success())

        service.addNewsTags(listOf("1", "2", "3"), listOf("some-tag-1", "some-tag-2", "some-tag-3"))
                .execute()

        server.verify("my-fake-service/edit-tag").called(
                times = once(),
                queryParams = params(
                        "a" to "some-tag-1",
                        "a" to "some-tag-6-fail",
                        "a" to "some-tag-3"))
}
````
