### ISSUE TITLE
Query parameter encoding issue

### ISSUE THREAD

**Issue by Tunous** [JorgeCastilloPrz/hiroaki#51]
```kt
// Definition
@POST("add-tag")
fun addTag(@Query("id") id: String): Call<Void>

// Usage
addTag("user/-/tag")

// Request: POST /add-tag?id=user%2F-%2Ftag HTTP/1.1

// Verification
server.verify("add-tag").called(queryParams = params("tag" to "user/-/tag"))
```

The following test fails at [this code fragment](https://github.com/JorgeCastilloPrz/hiroaki/blob/master/hiroaki-core/src/main/java/me/jorgecastillo/hiroaki/matchers/QueryParamsMatcher.kt#L42) where `user/-/tag` is compared to `user%2F-%2Ftag`.

**Comment by JorgeCastilloPrz** [comment]
Thanks for the report! I'm out of home these days but that's definitely a bug in the library. I'll fix it and deploy a new alpha version during the following week.

**Comment by JorgeCastilloPrz** [comment]
This has been fixed also and will start being available when the new version gets published.
