### ISSUE TITLE
Can't verify requests when using AndroidMockServerRule

### ISSUE THREAD

**Issue by shekibobo** [JorgeCastilloPrz/hiroaki#55]
I have verified that my tests are detecting and responding to requests with mocked responses as expected, but when I try to verify the requests on the server, I can never get any matches. The same verification code when using `MockServerRule` (instead of `AndroidMockServerRule`) can correctly verify the calls made during the request. I noticed that there aren't any tests for request verification in the `androidTest` source set.

I did try digging through the code around dispatchers, but I could not find anything standing out to me that was an obvious problem, since the code looks pretty much identical between the `AndroidDispatcherRetainer` and the `DispatcherRetainer`.

**Comment by JorgeCastilloPrz** [comment]
Yeah it seems to be a problem there. I'll take a look asap during the week. Thanks for reporting!

**Comment by shekibobo** [comment]
It looks like the web server may also not be having its `whenever` conditions reset after using the `AndroidMockServerRule`.  When my tests run in isolation, they pass just fine, but I'm having a few cases when I run the full suite, it is responding in one case with something that was set in an entirely different test for the same conditions.

**Comment by shekibobo** [comment]
I think I may have found part of the problem. `ServerExtensions.kt` has `whenever` methods that set the dispatcher to `DispatcherRetainer.hiroakiDispatcher`, but there's nothing to set them to `AndroidDispatcherRetainer.hiroakiDispatcher`. Might be that `AndroidDispatcherRetainer` should reference the static `DispatcherRetainer.hiroakiDispatcher` instead of its own instance. I suspect the same goes for the `queueDispatcher`.

**Comment by JorgeCastilloPrz** [comment]
I need to take a look at this tomorrow. Otherwise you can also open a PR today if you want to and I'll review it tomorrow. Thanks for the reports.

**Comment by JorgeCastilloPrz** [comment]
Release is done now. You can already fetch it. Let me know if you find any further problems on it pls!

**Comment by shekibobo** [comment]
Looks good, thanks!
