### ISSUE TITLE
Pause server

### ISSUE THREAD

**Issue by v-grishechko** [JorgeCastilloPrz/hiroaki#59]
Can I somehow pause the server? It's very useful, when testing progress during data loading. For example:
```kotlin
@Test
fun `test progress`() {
   server.pause()

   clickButton()
   assertProgressShow()

   server.resume()   

   assertContentShowed()
}
```

**Comment by JorgeCastilloPrz** [comment]
This library is based on extension functions over `MockWebServer`. That means you can do whatever you were able to do with it, since you have access to the server instance anytime. (i.e: you can start and stop it).
