### ISSUE TITLE
Update to use AndroidX version of test support library

### ISSUE THREAD

**Issue by shekibobo** [JorgeCastilloPrz/hiroaki#60]
Since Google I/O 2018, Espresso is now a part of the `androidx.test` package. Currently Jetifier is supposed to be able to replace imports used in third-party libraries, but for whatever reason it doesn't do so, either in `androidTest` build types or it's just not mapping `android.support.test` to `androidx.test`. 

If you try to upgrade to `androidx.test` version of things, everything crashes. I've reported the bug to google at https://issuetracker.google.com/issues/80006884.

Just leaving this here so that when `androidx.test` gets out of alpha/beta/rc, this library gets updated to use the new dependencies.

**Comment by josefadamcik** [comment]
@JorgeCastilloPrz  Maybe it's the time, AFAIK androidx.test is stable. 

I think it should be possible to support both - android.support.test and androidx.test. You can just add another small library that would be exactly the same as the hiroaki-android but would link androidx.test and use its InstrumentationRegistry.

If you don't' have time to look into that I could create a PR with such solution.

**Comment by JorgeCastilloPrz** [comment]
Sounds good, but I'm wondering if it wouldn't make more sense to just push androidx, and skip the double artifact deploys. People can still use the current version if they want a fully working copy of the library targeting support libraries. I'm not working on updates for Hiroaki so frequently anyways, so people will not miss any features on that version for a big while. They're gonna be forced to move on to androidx quite soon anyways, given that support 28 is the last one that will ever be released.

Thoughs?

**Comment by josefadamcik** [comment]
@JorgeCastilloPrz I think you are right, it should be ok to move  on to androidx since there is not much development happening in the project

**Comment by JorgeCastilloPrz** [comment]
Hi @josefadamcik and @shekibobo. I've deployed `0.1.0` now which targets AndroidX. Please bump the dependency in your projects if you're still using it and let me know if you have any problem.

https://github.com/JorgeCastilloPrz/hiroaki/releases/tag/0.1.0

**Comment by josefadamcik** [comment]
I confirm that it works for me. Thank you very much. 👍

**Comment by JorgeCastilloPrz** [comment]
Glad to hear. Thanks!
